title: Programmiersprachen und Theorie der Programmierung
author:
  name: Jan Christiansen
  email: jan.christiansen@hs-flensburg.de
description: >
  Hochschule Flensburg / Fachbereich 3 Information und Kommunikation / Angewandte Informatik

markdown: kramdown
remote_theme: jekyll/minima
minima:
  nav_pages:
    - topics.md
    - lectures.md
    - certification.md
